# Generated by Django 3.2.6 on 2021-08-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image2',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pics', verbose_name='Bild 2'),
        ),
        migrations.AddField(
            model_name='profile',
            name='image3',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pics', verbose_name='Bild 3'),
        ),
        migrations.AddField(
            model_name='profile',
            name='pinterest',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.TextField(help_text='ohne Adresse kein Wichteln. Falls du über die Feiertage wegfährst, bitte auch eine Ersatzadresse (+Zeitraum) angeben.', null=True, verbose_name='Meine Adresse'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image1',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pics', verbose_name='Bild 1'),
        ),
    ]
