# Generated by Django 3.2.6 on 2021-08-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210824_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='other',
            field=models.TextField(blank=True, help_text='hier ist Platz für weitere Anmerkungen', null=True, verbose_name='Sonstiges'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='allergies',
            field=models.CharField(blank=True, help_text='hier kannst du auch unterbringen, ob du Vegan bist/Alkohol trinkst etc.', max_length=250, null=True, verbose_name='Ich bin allergisch auf.../ich verzichte auf.../ich vertrage ... nicht'),
        ),
    ]
