# Generated by Django 3.2.6 on 2021-08-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='category',
            field=models.CharField(choices=[('kitchen', 'Gruß aus der Küche'), ('clothing', 'Kleidung'), ('accessory', 'Accessoires'), ('cosmetic', 'Kosmetik & Wellness'), ('papier', 'Schriftstücke & Bilder'), ('deko', 'Deko'), ('hhitem', 'Haushalt'), ('other', 'Sonstiges')], max_length=100, verbose_name='Kategorie'),
        ),
        migrations.AlterField(
            model_name='wish',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Anfängerfreundlich'), ('medium', 'Anspruchsvoll'), ('hard', 'Schwierig')], help_text='Deine Einschätzung: muss man in der Technik schon sehr bewandert sein, oder schafft das auch ein Anfänger?', max_length=100, verbose_name='Schwierigkeitslevel'),
        ),
    ]
