# Generated by Django 3.2.6 on 2021-08-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0002_auto_20210825_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Anfängerfreundlich'), ('medium', 'Anspruchsvoll'), ('hard', 'Schwierig')], help_text='Deine Einschätzung: schafft das auch ein Anfänger? Oder sollte man etwas mehr Erfahrung haben?', max_length=100, verbose_name='Schwierigkeitslevel'),
        ),
        migrations.AlterField(
            model_name='wish',
            name='trackingnr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
